### ISSUE TITLE
Podjąć decyzje co do designu UI (przynajmniej wstępne)

### ISSUE THREAD

**Issue by birgoth** [nowrek/NewsFilter#2]

**Comment by rukeros** [comment]
Sending for review.
commit: ed2e6186ffa124650080847e3f09cf5012692e15

**Comment by birgoth** [comment]
Proponuję inne podejście do designu UI.
Poprawka pomyłki:
0cb15d662c2601ef2ad8959d6866ec5881e5e5de
Commit właściwy:
576e1c227b679649d13e011bf381fd273de879a8

**Comment by rukeros** [comment]
Jest tylko problem, że nie mieści się to na stronie w PDFie i nie widać dołu apki :P
